### ISSUE TITLE
Crash while siege

### ISSUE THREAD

**Issue by rgmoon** [Norbivar/RTSCamera#13] opened 2023-07-13 16:37 UTC
You can tun outside the castle when you are defense enemy.
And force siege ram stop.
Then when enemy was retreat the crash happened！
Here is the crash report

https://report.butr.link/4383F5.html

感覺你好像是中國人，所以我用中文來說明應該會比較清楚
我在當防守方的時候，騎馬可以越過城牆去騷擾進攻方的衝車。
敵方的衝車會沒辦法繼續前進，城牆上的弓箭手可以持續殺敵，敵人會乖乖站在原地給你射
但是過沒多久他們應該是士氣不夠了要撤退時，遊戲會崩潰，不確定是不是因為衝車推不到位產生的
頗確定應該是這個模組造成的，不知道是不是因為戰鬥AI有被重新編寫，當用這個模組的時候敵人才會乖乖給你射
停用這個模組的時候他們則會一直持續嘗試推車，被騷擾時也不會乖乖站在原地。
這是崩潰報告
https://report.butr.link/4383F5.html

**Comment by Norbivar** [comment] 2023-07-14 10:22
What makes you think it was this mod?
Stacktrace has no mention of it at all, not to say you have quite a lot of other mods installed..

**Comment by rgmoon** [comment] 2023-07-14 13:16
It happened when I enable this mod.
And when I disable it the problem solved.

**Comment by duzhoufei** [comment] 2023-07-15 02:26
Yes i have the same problem.When I am attacking a city, especially when I enter the city, I will definitely crash out. And when I disable this mod, nothing happens,problem solved. And I have seen the above issues caused by enabling this mod on forums and other websites. Please fix it. This mod is very excellent!

**Comment by yds725** [comment] 2023-07-16 06:04
I have exact same crash too. That crash report is exactly matched as mine. I deleted all save files and even reinstalled games. Bc if i disable rts mod and keep playing on old save, i am not sure that save file will still be stable.
I really like this mod. 
Crash always happen only on siege (I was defense side). It does work great on normal battle. I played on 1.1.5 version though. I used rts mod for 1.1.2

**Comment by Norbivar** [comment] 2023-07-18 06:12
Yeah, there are some weird crashes on in the sieges, but no matter how I try, I cannot pinpoint any function in the mod to be responsible.
Like nothing in the code remotely does what the crashes are all about.

**Comment by rgmoon** [comment] 2023-07-18 07:32
I've notice that there are many diffirent but similar crash report
sometime it point at Retreat sometime it point at SwitchUnitLocations
But they all point at MBList2D.set_Item and LineFormation function
Is RTS camera agent conflic with orginal AI?
I think the problem is RTS camera agent

**Comment by Norbivar** [comment] 2023-07-18 09:45
Yeah, they are all related to retreat "phase". Sometimes there are agents which get their team set to NULL which is then dereferenced, sometimes these overindexing bugs appear.
But there isn't anything in the code that would warrant anything like these.

**Comment by faruk1927** [comment] 2023-07-18 19:30
Exact issue for me too. i cant enter to a siege. after a while i am getting CDT
-
-
-
Exception information
Type: System.IndexOutOfRangeException
Message: Index was outside the bounds of the array.
Source: TaleWorlds.Library
CallStack:
at void TaleWorlds.Library.MBList2D.set_Item(int index1, int index2, T value)
at void TaleWorlds.MountAndBlade.LineFormation.RelocateUnit(IFormationUnit unit, int fileIndex, int rankIndex)
at void TaleWorlds.MountAndBlade.LineFormation.FillInTheGapsOfFileAux(LineFormation formation, int fileIndex, int rankIndex)
at void TaleWorlds.MountAndBlade.LineFormation.FillInTheGapsOfFile(LineFormation formation, int fileIndex, int rankIndex, bool isCheckingLastRankForEmptiness)
at void TaleWorlds.MountAndBlade.LineFormation.RemoveUnit(IFormationUnit unit, bool fillInTheGap, bool isRemovingFromAnUnavailablePosition)
at void TaleWorlds.MountAndBlade.Formation.RemoveUnit(Agent unit)
at void TaleWorlds.MountAndBlade.Agent.set_Formation(Formation value)
at void TaleWorlds.MountAndBlade.Agent.OnRemove()
at void TaleWorlds.MountAndBlade.Mission.OnAgentRemoved(Agent affectedAgent, Agent affectorAgent, AgentState agentState, KillingBlow killingBlow)
at void ManagedCallbacks.CoreCallbacksGenerated.Mission_OnAgentRemoved(int thisPointer, int affectedAgent, int affectorAgent, AgentState agentState, KillingBlow killingBlow)
at void TaleWorlds.MountAndBlade.Agent.Die(Blow b, KillInfo overrideKillInfo)
at void XorberaxLegacy.Logic.DeadlyCombatMissionLogic.OnRegisterBlow(Agent attacker, Agent victim, GameEntity realHitEntity, Blow blow, ref AttackCollisionData collisionData, in MissionWeapon attackerWeapon)
at void TaleWorlds.MountAndBlade.Mission.RegisterBlow(Agent attacker, Agent victim, GameEntity realHitEntity, Blow b, ref AttackCollisionData collisionData, in MissionWeapon attackerWeapon, ref CombatLogData combatLogData)
at void TaleWorlds.MountAndBlade.Mission.MeleeHitCallback_Patch1(Mission this, ref AttackCollisionData collisionData, Agent attacker, Agent victim, GameEntity realHitEntity, ref float inOutMomentumRemaining, ref MeleeCollisionReaction colReaction, CrushThroughState crushThroughState, Vec3 blowDir, Vec3 swingDir, ref HitParticleResultData hitParticleResultData, bool crushedThroughWithoutAgentCollision)
at void ManagedCallbacks.CoreCallbacksGenerated.Mission_MeleeHitCallback(int thisPointer, ref AttackCollisionData collisionData, int attacker, int victim, NativeObjectPointer realHitEntity, ref float inOutMomentumRemaining, ref MeleeCollisionReaction colReaction, CrushThroughState crushThroughState, Vec3 blowDir, Vec3 swingDir, ref HitParticleResultData hitParticleResultData, bool crushedThroughWithoutAgentCollision)
at void TaleWorlds.MountAndBlade.Mission.Tick_Patch2(Mission this, float dt)

**Comment by Norbivar** [comment] 2023-07-19 07:57
Some circumstance must be eluding me.
Can you describe exactly what happens leading to the crash?
Do you die?
Do you switch characters?

Because only these are the only scenarios that affect Formations (adding/removing characters).

**Comment by rgmoon** [comment] 2023-07-19 18:43
> You can tun outside the castle when you are defense enemy. And force siege ram stop. Then when enemy was retreat the crash happened！ Here is the crash report
> 
> https://report.butr.link/4383F5.html
> 
> 感覺你好像是中國人，所以我用中文來說明應該會比較清楚 我在當防守方的時候，騎馬可以越過城牆去騷擾進攻方的衝車。 敵方的衝車會沒辦法繼續前進，城牆上的弓箭手可以持續殺敵，敵人會乖乖站在原地給你射 但是過沒多久他們應該是士氣不夠了要撤退時，遊戲會崩潰，不確定是不是因為衝車推不到位產生的 頗確定應該是這個模組造成的，不知道是不是因為戰鬥AI有被重新編寫，當用這個模組的時候敵人才會乖乖給你射 停用這個模組的時候他們則會一直持續嘗試推車，被騷擾時也不會乖乖站在原地。 這是崩潰報告 https://report.butr.link/4383F5.html

Translate by chatgpt-chinese part
 
When I am on the defensive side, I can ride a horse to cross over the city walls and harass the attacking forces' siege engines. The enemy's siege engines become unable to advance, and our archers on the walls can continuously eliminate the enemy, causing them to stay in place, allowing us to shoot them down.

However, after a while, it seems their morale drops, and they start to retreat, causing the game to crash. I am not sure if it's due to the siege engines not being pushed properly or if the combat AI has been rewritten. When using this module, the enemies behave as expected and stand still to be shot at. But when I disable this module, they continue trying to push the siege engines and don't stay in place, even when being harassed.

**Comment by Norbivar** [comment] 2023-07-19 19:28
The most I can do at this point is to disable all code hooks and reenable them one by one, as nothing stands out to do anything close to the described things. Hell, this is bound to take some time and life-force...
But it's weird, because it is reproducible. I'll try updating the referenced Harmony as well, just in case.

**Comment by Norbivar** [comment] 2023-07-25 09:23
> Is RTS camera agent conflic with orginal AI?

Seems like it does. The culprit seems to be that part of the code, even if it just handles the "outlining" of the characters.

**Comment by Norbivar** [comment] 2023-07-25 15:17
@rgmoon Should be fixed now!

**Comment by rgmoon** [comment] 2023-07-25 18:19
Is it compatible with 1.1.4?

**Comment by Norbivar** [comment] 2023-07-25 18:50
Oh wait, you were not on beta branch. 
Well, I might be able to create one sometime if really needed.

**Comment by rgmoon** [comment] 2023-07-25 19:38
Please, I beg u ;_;

**Comment by Norbivar** [comment] 2023-07-25 20:40
Please try these.
These were made for 1.1.5, but I hope they will work with 1.1.4.

[RTSCamera.zip](https://github.com/Norbivar/RTSCamera/files/12165424/RTSCamera.zip)
[RTSCamera.CommandSystem.zip](https://github.com/Norbivar/RTSCamera/files/12165426/RTSCamera.CommandSystem.zip)

**Comment by Norbivar** [comment] 2023-07-27 07:57
This should be better:
https://github.com/Norbivar/RTSCamera/releases/tag/unofficial-release-v4.1.23.0-for-bannerlord-v1.1.5

**Closed as completed** 2023-11-05 19:27 UTC
