### ISSUE TITLE
Switching to another hero while the main hero is still alive freezes/crashes the game

### ISSUE THREAD

**Issue by LuciusKeuchhustus** [Norbivar/RTSCamera#7] opened 2023-04-27 23:28 UTC
I tried using the "select another hero" function, but upon pressing F to control the selected hero, the game freezes. Controlling another hero when the main hero is knocked out works perfectly fine. I'm playing on 1.1.3 with the newest version of this mod (for 1.1.2). This is the only problem I have encountered so far, otherwise the mod works great. Thank you for you great work, btw :)

**Comment by Norbivar** [comment] 2023-05-01 14:09
Cannot reproduce just by doing these, so it could be something else also at work here.

**Comment by LuciusKeuchhustus** [comment] 2023-05-01 18:00
I tried deactivating some mods that may somehow conflict with this, but the crash still happens. Watching another hero while the main hero is still alive works fine, but as soon as I press F to control that hero, the game freezes for some seconds and then closes. I even tried binding the control character function to Q to test, if it perhaps somehow conflicted with the native "fast forward" function, which is also bound to F, but he crash still happened the same. 
Perhaps I simply did not deactivate the right mods, most times the crashes one gets are related to mods you would have never thought of xD 
I really don't know what's wrong on my end, I love the function to switch characters and I used it perfectly fine all the time with the original mod on earlier versions of the game.

**Comment by Norbivar** [comment] 2023-05-01 18:27
So it crashes, too?
Do you have maybe a callstack for that?

**Comment by LuciusKeuchhustus** [comment] 2023-05-01 21:24
Sorry, I should have called it CTD instead of crash. No, I get no crash report, not even the normal error message where you can click on "ignore this problem -yes -no". The game simply freezes for a few seconds and then closes, as if I had used Alt-F4 or something.

**Comment by Norbivar** [comment] 2023-05-03 17:05
That's definitely not a good sign, because then it's even more untraceable.
I would like to recommend a clean reinstall (not an integrity check) first, since the problem since to occur only on your end - so far.
Without any callstacks, clear and able reproduction steps, I sadly cannot help you further. :/

**Comment by LuciusKeuchhustus** [comment] 2023-05-07 15:21
I tried around for a bit to see if I can somehow fix it, but it still happens. Weirdly, I can switch characters without problem during a  siege. But upon trying to control another hero during a field battle, it instantly CTD's the game. I'll see if I can find out more, but for now, I'll simply have to refrain from changing characters during battle

**Comment by cifrenelazu** [comment] 2023-07-26 13:39
Yeah, I have been having the same CTD.
When main character dies, and then switch to another character everything works fine, but when switching to another character without main character dying it just freezes for a second and exits the game with no prompts, log entries or anything. Do you know where I could dig for some info on why the game crashed to help you fix this?
I don't use a lot of mods and this is a fresh install, game and mod.

EDIT: This is the only situation where the game is crashing, camera and commands work as intended in every other aspect.

EDIT 2: I do think it is somehow connected to main character state - dead/alive, as that is the only difference.

EDIT 3: So what I found out is that main hero presence on the battlefield is the factor.
I have put main character in separate formation. After the battle starts, I go to free look camera, command the main hero formation, with just the hero in it, to retreat. After main hero retreats, you can choose to play with any other entity, any time you want. Better for hero to retreat than to die, if you want to level up companions.

**Comment by Norbivar** [comment] 2023-07-26 15:21
I'll try to look into it. By default, the death should not matter - or at least I have not encountered any crash so far changing agents alive or dead.
But the retreat case could make sense, so I'll give it a look.
Otherwise I'd love some game versions here + used mod version.

**Comment by cifrenelazu** [comment] 2023-07-26 20:26
Game version is 1.1.5.21456
Mod version is v4.1.23.0 - titled here on git Release RTS Camera v4.1.23 for Bannerlord v1.1.2 master
should I try the new version with siege fix, although i had no problems in sieges whatsoever, excluding switching characters while main hero is alive?

**Comment by Norbivar** [comment] 2023-07-26 21:51
I would advise to try that "newer" release, since that was compiled against 1.1.5 Bannerlord code, and that has the best chance of succeeding. 
If the issue still there, I will take a closer look at whether I can reproduce it or not.

**Comment by cifrenelazu** [comment] 2023-07-27 21:25
No, still CDT's when switching heroes while main character still alive...
Where in the mod list should RTS Camera be? Maybe that is the problem?

**Comment by Norbivar** [comment] 2023-07-28 04:03
I do not think that should be the problem, but you can play around with it.
I can promise to look at it only in 2 weeks time as I will be far from home.

**Comment by Norbivar** [comment] 2024-08-24 09:55
I have not heard anything like that ever since, nor did I found anything on my end related to this.
I am closing this for sanity, if it persists by any chance, feel free to open another one.

**Closed as not planned by Norbivar** 2024-08-24 09:55 UTC
